version: '3.4'
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app_0
    restart: always
    expose:
      - 6000
    environment:
      - CUEAPP_VERSION=0.0.1
      - CUEAPP_DEVELOPMENT=true
      - CUEAPP_TESTING=false
  cueclient:
    build: cueclient
    container_name: cueclient_0
    expose:
      - 4000
    environment:
      - CUECLIENT_VERSION=0.0.1
      - CUECLIENT_TESTING=true
  #tests:
  #  build:
  #    context: app
  #   dockerfile: Dockerfile-tests
  #  container_name: tests_0
  #  environment:
  #    - CUEAPP_TESTING=True
  auth:
    container_name: auth_0
    build: auth
    expose:
      - 4180
  openresty:
    container_name: openresty_local_0
    build:
      context: openresty
      dockerfile: Dockerfile-local
    links:
      - app
    ports:
      - 80:80
