version: '3.4'
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app_0
    restart: always
    expose:
      - 6000
    environment:
      - CUEAPP_VERSION="0.0.1"
      - CUEAPP_DEVELOPMENT=True
      - CUEAPP_TESTING=False
  openresty-ssl:
    container_name: openresty_0
    build:
      context: openresty
      dockerfile: Dockerfile-ssl
    links:
      - app
    ports:
      - 80:80
      - 443:443